# Generated by Django 4.2.3 on 2023-07-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publication_date',)},
        ),
    ]
